name: 블로그 동기화

on:
  push:
    branches:
      - main

jobs:
  BuildAndSync:
    name: 빌드 및 동기화
    runs-on: ubuntu-latest
    steps:
      - name: 리포지토리 체크아웃
        uses: actions/checkout@v4
      - name: Node.js 셋업
        uses: actions/setup-node@v4
        with:
          node-version: '22.2'
      - name: 패키지 설치
        run: npm ci
      - name: 테스트 수행
        run: npm build
      - name: 테스트 로그 출력
        run: echo test